### ISSUE TITLE
BiliBili也有个开源的弹幕库=_=

### ISSUE THREAD

**Issue by Piasy** [linsea/OpenDanmaku#3]
https://github.com/Bilibili/DanmakuFlameMaster

**Comment by linsea** [comment]
@Piasy 看过那个库，它的用户接口太重，太复杂难用了，主要是无法满足我的需求，所以我就自己写了这个轻量级的库，你可以发现，用户接口非常简单好用。

**Comment by Piasy** [comment]
Nice!
