### ISSUE TITLE
修改弹幕字体大小时出现黑色背景

### ISSUE THREAD

**Issue by zhangshexin** [linsea/OpenDanmaku#7]
我在发弹幕时修改了字体大小
IDanmakuItem item = new DanmakuItem(this, new SpannableString(input), mDanmakuView.getWidth(),0,R.color.my_item_color,18,1)
其他弹幕的字体大小是14号字，显示时会有黑色的背在弹幕上出现

**Comment by zhangshexin** [comment]
刚才去掉描边后发现是出现的重影

**Comment by zhangshexin** [comment]
已经找到问题， borderStaticLayout.draw(canvas);注掉就可以了

**Comment by Leon0913** [comment]
楼上的大兄弟太棒了，我找了好久都没找到原因。。。
